example.property= I AM DEV

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#``````````````````````````````````````````````````````JPA CONFIGS``````````````````````````````````````````````````````
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/spmia-realm

spring.datasource.url = jdbc:postgresql://pg-1f2a7dcb-yomallearning-5abc.b.aivencloud.com:22078/ostock_dev?sslmode=require
spring.datasource.username = avnadmin
spring.datasource.password = ${DB_PWD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url = jdbc:postgresql://localhost:5432/ostock_dev
#spring.datasource.username = postgres
#spring.datasource.password = postgres

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#``````````````````````````````````````````````````````ZIPKIN CONFIGS```````````````````````````````````````````````````
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# # sampling.probability=1.0 traces 100% of requests — fine for local/dev learning, but you'd dial this down (e.g. 0.1) in a real production deployment.                                                                                                                                                                                     
# management.tracing.sampling.probability=1.0  
# management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans                                                                                                                                                             
                                                                            